### ISSUE TITLE
Subpaths of mountpoint url are not respected

### ISSUE THREAD

**Issue by Buuhuu** [adobe/helix-html2md#90]
**Description**
Consider the following fstab.yaml
```
mountpoints:
  /: 
    url: https://98cc-192-147-117-11.ngrok.io/content/franklin-examples
    type: markup
    suffix: ".html"
```

If previewing `/` using 

```
curl -X POST https://admin.hlx.page/preview/owner/project/ref/ 
```

a request to https://98cc-192-147-117-11.ngrok.io/content/franklin-examples/index.html would be expected, but actually https://98cc-192-147-117-11.ngrok.io/index.html is requested.

This is caused by https://github.com/adobe/helix-html2md/blob/main/src/index.js#L69

```
url = new URL(relPath, mp.url).href;
```

as the relPath is relative to the mountpoint (`/` in the example above) and replaced the full pathname of the url.
